- core/basic_models/actions/string_actions.py
- tests/core_tests/basic_scenario_models_test/action_test/test_action.py
Исправление несинхронного рандома bubble и pronounceText. 
Если количество элементов каждого поля одинаково, то будет выбран элемент с одним и тем же номером. В случае неодинакового количества, генерируется случайное число по максимальному, и для других используется остаток от его деления на длину списка.
> DPNLPF-1299 sdk action

- core/model/base_user.py
Добавлен key_name=user_save в base_user, добавлен лог про Saving User.
Для задачи DPNLPF-1389:
схлопнуть в одно сообщение логи - Saving User и DialogPolicyUser.raw USER
> DPNLPF-1389 in base_user added key_name=user_save

- core/message/from_message.py
- tests/core_tests/mq_test/test_from_message.py
Remove sub from db_uid to support prevention of the same user after authorization.
> DPNLPF-1628 remove sub from db_uid

- .github/workflows/python-package.yml
- setup.py
- tests/core_tests/descriptions/test_descriptions.py
- tests/core_tests/model_test/test_model.py
- tests/core_tests/operators_test/test_comparators.py
- tests/core_tests/operators_test/test_operators.py
- tests/core_tests/repositories_test/test_repo.py
- tests/core_tests/requirements_test/test_requirements.py
- tests/scenarios_tests/requirements_test/test_requirements.py
Fix error https://pastebin.com/FCLYBjk7 in tests
> Freeze protobuf

- core/logging/logger_utils.py
- core/message/from_message.py
- core/utils/masking_message.py
- scenarios/scenario_models/field/field.py
- smart_kit/message/smartapp_to_message.py
- tests/core_tests/masking_test/masking_test.py
Теперь маскирование происходит не inplace а собирается в отдельный результирующую переменную
> Изменение маскирования

- smart_kit/start_points/main_loop_kafka.py
добавить логгирование значения mq_message.key() (т.е. значения ключа сообщения (принимаемого и посылаемого в kafka)) в отдельное поле при логгировании входящего и исходящего запроса в nlpf
> DPNLPF-1728: log message_key in incoming message log and outgoing message log

- core/logging/logger_utils.py
DPNLPF-1700 установка значений времени хранения логов по умолчанию log_store_for=1
> DPNLPF-1700 default log_store_for=1

- core/logging/logger_utils.py
- smart_kit/handlers/handle_respond.py
для событий логирования process_time заполняется поле surface
> DPNLPF-1743

- scenarios/actions/action.py
- scenarios/scenario_descriptions/form_filling_scenario.py
- scenarios/scenario_descriptions/tree_scenario/tree_scenario.py
- scenarios/scenario_models/history/formatters.py
- scenarios/scenario_models/history/history.py
- tests/scenarios_tests/actions_test/test_action.py
- tests/scenarios_tests/scenario_models_test/test_history.py
По требованию хистори нужно поменять имя поля, и обновить все аппы
> Rename history field

- core/message/device.py
Новые атрибуты:
string ram_gb = 12; //Количество гигабайт оперативной памяти на устройстве, пример: 2
string cpu = 13; //Тактовая частота устройства в Ггц, пример: 4
> PNLP-4944: add ram_gb and cpu for device

- core/db_adapter/memory_adapter.py
не стал плодить сущности, думаю достаточно одного локального адаптера, название устоялось - его и оставил
> memory adapter = cache adapter

- core/message/from_message.py
Сделал особую валидацию для сообщений PUSH_RESULT и других от сервиса SmartPush, которая проверяет только те поля, которые реально приходят.
> DPNLPF-2067: fix validation of push answers | add msg_name to required_fields map

- .gitignore
- smart_kit/utils/logger_writer/logger_formatter.py
- tests/smart_kit_tests/logging/test_logger_formater.py
Фикс ошибки добавления полей при итерации по словарю. Доработка заключается в создании нового словаря, и выдаче его. 
Также написал тесты на кастовалку логов
> Fix log casting

- smart_kit/configs/settings.py
Проблема: из template_config не вычитывается поле kafka_use_secrets_path: false
> DPNLPF-2072: fix template_settings_repo.load

- smart_kit/configs/__init__.py
Все пути в app_config можно задавать через os.env
> PNLP-7713: add read all paths in app_config from os.env

- smart_kit/start_points/main_loop_kafka.py
Удалил нигде не используемый созданный тред
> DPNLPF-1959: remove rudimentary publisher thread

- smart_kit/start_points/main_loop_kafka.py
> fix queue_index

- smart_kit/resources/__init__.py
add FolderRepository for classifiers in SmartAppResources.__init__
> classifiers

- core/basic_models/actions/variable_actions.py
- core/basic_models/variables/mid_variables.py
- core/utils/stats_timer.py
- scenarios/actions/action.py
- scenarios/user/user_model.py
- smart_kit/models/smartapp_model.py
- smart_kit/resources/__init__.py
- smart_kit/start_points/main_loop_kafka.py
- tests/pure_framework/smart_kit_tests/user/test_user_model.py
- tests/pure_framework/smart_kit_tests/utils/stats_timer.py
- tests/pure_framework/smart_kit_tests/utils/test_stats_timer.py
1. Добавил отправку payload.stats из навыка
2. Доработал StatsTimer для рассчёта inner_stats
Пример конфигурирования в навыке: https://stash.sigma.sbrf.ru/projects/SBERBANKBOT/repos/dialog_policy/pull-requests/1937/diff#app_with_stats%2Fapp%2Fbasic_entities%2Factions.py
> PNLP-12553: add stats

- core/repositories/secret_file_repository.py
- smart_kit/configs/settings.py
add secrets for template_settings
> DPNLPF-2276 add secrets for template_settings

- smart_kit/start_points/main_loop_kafka.py
DPNLPF-2349 add default for stats.optional
> DPNLPF-2349 add default for stats.optional
