smart_kit/start_points/main_loop_kafka.py

The fix of modifying of kafka_config by KafkaPublisher and KafkaConsumer initialisers is done in the pull request. The modification affected possibility of applying pickle_deepcopy on user.settings and consequently params of actions and scenarios.

fix modification of config by kafka utils in kafka main loop

---

core/configs/global_constants.py
core/message/from_message.py
core/model/base_user.py
core/request/kafka_request.py
scenarios/user/user_model.py
smart_kit/request/kafka_request.py
smart_kit/start_points/main_loop_kafka.py
tests/smart_kit_tests/request/test_kafka_request.py
tests/smart_kit_tests/user/test_user_model.py

Если в исходном сообщении в headers приходит ключ "kafka_replyTopic", то "пытаемся" послать ответ в этот топик.
Под "пытаемся" понимается, что если сгенерированный outgoing_request уже содержал в себе топик, например если в action было указано "request_data": {"topic_key": "smth", ...}, то мы посылаем запрос в тот топик, что указан. А вот если знания о том, куда отправлять запрос нет, то посылаем в "kafka_replyTopic".

DPNLPF-1692 Reply to topic "kafka_replyTopic" if it exists in message headers

---

core/mq/kafka/kafka_publisher.py
core/request/kafka_request.py
smart_kit/start_points/main_loop_kafka.py

поломка mq_message.key() (т.е. значения ключа сообщения (принимаемого и посылаемого в kafka)) на совести аппа - от этого сложно гарантированно защититься
сейчас когда ответ аппа ломает входящий ему mq_message.key() - дальнейшее взаимодействие так же идет с ломанным mq_message.key()
хотя DP может восстановить правильное значение mq_message.key() из DialogPolicyFromMessage (свойства sub, channel, uid)
необходимо реализовать такую логику
От Макара: добавил восстановаление Kafka message key, отрефакторил check_message_key, дополнительно поправил форматирование и добавил Type-хинты.
Для проверяющего: логика меняется только в четырёх местах, а остальное - форматирование. По изменению логики: self.check_message_key - замена вызова функции на равносильный код; вызов self._send_request - передача …

DPNLPF-1729: add recovery of Kafka message key, refactor check_message_key, reformatting

---

smart_kit/start_points/main_loop_kafka.py

Проблема заключалась в том, что сообщение перепосылалось дважды, если kafka_key был невалидный. Это происходило из-за обертки обработки сообщения в цикле while, который не встречал стоп-условия после пересылки сообщения.
В ПРе был добавлен break для предотвращения повторной обработки сообщения.

DPNLPF-1728: fix double message when invalid message key

---

smart_kit/start_points/main_loop_kafka.py
smart_kit/template/static/configs/template_config.yml

улучшить логгирование при поломке ключа кафки
- в запись лога с key_name = check_kafka_key_validation убрать запись поля args.data как избыточное
- в запись лога с key_name = kafka_message_key_recovery убрать запись поля args.data как избыточное
- запись лога с key_name = kafka_message_key_recovery перенести на levelname=DEBUG как избыточное для отладки в проме

DPNLPF-1842: change kafka key log fields

---

smart_kit/start_points/main_loop_kafka.py
smart_kit/template/static/configs/template_config.yml

запись лога с key_name = kafka_message_key_recovery перенести на levelname=DEBUG как избыточное для отладки в проме

DPNLPF-1842: fix kafka_message_key_recovery_log_level

---

scenarios/actions/action.py

RuntimeError: dictionary changed size during iteration
https://github.com/salute-developers/smart_app_framework/blob/09348ccd05d96785525c8dd5a88d0836442c2822/scenarios/actions/action.py#L512-L514
словарь нельзя менять во время итерации

DPNLPF-1890: proper delete of the keys from the keys_to_pop

---

smart_kit/start_points/main_loop_kafka.py

+ fixed `topic_key` in log message (KeyError)
we've lost a key name some where
https://github.com/salute-developers/smart_app_framework/blob/v1.0.7rc22/smart_kit/start_points/main_loop_kafka.py#L403-L405

Fix outgoing log message

---

core/basic_models/actions/basic_actions.py
core/basic_models/scenarios/base_scenario.py
scenarios/actions/action.py
scenarios/behaviors/behaviors.py
scenarios/scenario_descriptions/form_filling_scenario.py
scenarios/scenario_descriptions/tree_scenario/tree_scenario.py
smart_kit/handlers/handle_respond.py
smart_kit/handlers/handle_server_action.py
smart_kit/handlers/handle_take_runtime_permissions.py
smart_kit/handlers/handler_base.py
smart_kit/models/smartapp_model.py
smart_kit/system_answers/nothing_found_action.py

Проблема: разработчики навыков на фреймворке столкнулись с Exception'ами после доработки https://github.com/salute-developers/smart_app_framework/pull/46, которая исключила поддержку None в качестве ответа Action.run.
Что сделал: решил проблему путём валидация ответа через 'result or []' в местах, уязвимых для None значений.
Теперь следующие утверждения верны:
- Scenario.run возвращает List[Command]
- Action.run во фреймворке всегда возвращает List[Command]
- Action.run аппа возвращает Optional[List[Command]]
- Behaviors.{success, timeout, fail} возвращает List[Command]
- Handler.run во фреймворке возвращает List[Command]
- Handler.run аппа возвращает Optional[List[Command]]

DPNLPF-1910: support none as answer of actions and handlers

---

core/db_adapter/ceph/ceph_adapter.py
core/db_adapter/db_adapter.py
core/db_adapter/ignite_adapter.py
core/mq/kafka/async_kafka_publisher.py
core/mq/kafka/kafka_consumer.py
core/mq/kafka/kafka_publisher.py
core/request/rest_request.py
core/unified_template/unified_template.py
core/utils/rerunable.py

Проблема: апп кидает рейсы, когда происходит обращение к monitoring.monitoring.поле (инстансу from core.monitoring.monitoring import monitoring), так как такого поля больше нет у инстанса, это легаси.
```
monitoring.monitoring.pod_event(self.app_name, POD_UP)
File "/Users/19134925/Documents/Documents/Code/Sber/framework_testing/smart_app_framework/core/monitoring/monitoring.py", line 314, in __getattr__
return getattr(self.instance, item)
AttributeError: 'Monitoring' object has no attribute 'monitoring'
```
Решение: заменить обращение monitoring.monitoring.поле на monitoring.поле.

DPNLPF-1885: fix monitoring access

---

scenarios/scenario_models/field/composite_fillers.py

Проблема: RequirementFiller, ChoiceFiller и ElseFiller перестали работать, потому что стали в любом случае считаться заполненными. Если говорить конкретнее, то поломка случилась из-за наследования от Action'ов, которые стали возвращать пустой список по дефолту. А от филлеров при незаполнении ожидается None.
Решение: возвращаение None в проблемных филлерах в случаях незаполнения.

DPNLPF-1894: fix fillers

---

core/basic_models/actions/basic_actions.py
core/basic_models/actions/counter_actions.py
core/basic_models/actions/variable_actions.py
scenarios/actions/action.py
smart_kit/message/smartapp_to_message.py
smart_kit/system_answers/nothing_found_action.py
smart_kit/template/app/basic_entities/actions.py-tpl
tests/core_tests/basic_scenario_models_test/action_test/test_action.py
tests/scenarios_tests/actions_test/test_action.py

Проблема: вызывается два запроса вместо одного из-за "наследования" логики метода run() у акшнов. 
Пример проблемы: при использовании self_service_with_state сообщение отправляется два раза из-за того, что тут используется action BaseSelfServiceWithState, где в run сначала выполняется super().run(), который и так генерирует команду отправки сообщения и метод self._run, который генерирует точно такую же команду.  В результате сообщение отправляется два раза. 
Решение: убрал "наследование" логики через super().run() в акшнах, где она не нужна, чтобы избежать этого и других возможных инцидентов.

DPNLPF-1925:fix message dubling by removing super run in actions

---

smart_kit/start_points/main_loop_kafka.py

Проблема: склеиваются логи "Publishing time: {} msecs" из-за отсутствия \n в конце.
Решение: добавить \n в конце проблемного лога.

DPNLPF-1991: Fix log Publishing time

---

smart_kit/start_points/main_loop_kafka.py

Добавлен функционала пропуска сообщений из кафки, которые пролежали больше таймаута по app_request. Дефолтная длительность таймаута - таймаут для app_request на b2c (8 сек).
Доработку протестировал на локально поднятом навыке. Навык пропускает обработку + error log, если сообщению 8 сек+, или пишет warning, но обрабатывает, если сообщению 0.2 сек+.

Feature/DPNLPF-1943: skip old message

---

smart_kit/handlers/handle_respond.py
smart_kit/handlers/handle_server_action.py
smart_kit/handlers/handler_timeout.py

Проблема: дублируются метрики по количеству входящих сообщений в HandlerRespond, HandlerServerAction и HandlerTimeout. Из-за этого навыки не могут пройти НТ.
Решение: удалён повтор отправки метрик в Handlers.

DPNLPF-2013: remove dubbling of monitoring.counter_incoming in handlers

---

core/basic_models/actions/client_profile_actions.py
core/configs/config_constants.py
core/logging/logger_utils.py
core/mq/kafka/kafka_publisher.py
core/request/kafka_request.py
smart_kit/request/kafka_request.py

Новый функционал: задание header'а `kafka_replyTopic` через указание `reply_topic_key` в `Command.request_data` (для акшнов, отнаследованных от `CommandAction`, этому соответствует итем `request_data`) в соответствие с маппингом из конфига перед отправкой запроса. Маппинг задаётся в конфиге так: в конфиге `template_config.yml` в поле `reply_topic` указывается набор ключ-значений в формате `reply_topic_key: kafka_replyTopic`. `reply_topic_key` имеет приоритет над `kafka_replyTopic`, то есть в случае наличия обоих полей выберется `reply_topic_key`.

PNLP-7328: map reply_topic_key to kafka_replyTopic before kafka request

---

smart_kit/testing/suite.py

Возможность переобъявить сравнение ответов и юзера в дочерних классах. Поможет выполнять проверки служебных сообщений в History в DP

Redefine testsuite compare

---

scenarios/scenario_descriptions/form_filling_scenario.py

- add masking for logging data_extracted_str

feature/form-filling-scenario-params-masking:

---

smart_kit/start_points/main_loop_async_http.py

При базовом классе AIOHttpMainLoop происходила ошибка при старте. Сервер не мог стартовать и падал в методе AIOHttpMainLoop.get_db на строчке self.app.on_cleanup.append(self.close_db), тк объекта аппа еще не существует. Правка примитивна

bug/incorrect-aiohttp-app-init:

---

core/db_adapter/ignite_adapter.py

Были несостыкованы питонячие интерфейсы. `DBAdapter` при ошибке подключения внутри `self._async_run` вызывал `self._on_prepare`, который был частью логики восстановления соединения. Но вызов происходил синхронно, а в `IgniteAdapter` интерфейс метода асинхронный, поэтому логика не отрабатывала. Я исправил интерфейс метода в `IgniteAdapter`.

PNLP-8011: fix ignite reconnect

---

.github/workflows/python-package.yml

update ubuntu for GitHub actions runner since previous version (20.04) is deprecated

DPNLPF-2339: update ubuntu version from 20.04 to 24.04
